stages:
  - format

format_cpp:
  stage: format
  image: ubuntu:24.04
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends wget gpg software-properties-common
    - wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor > /usr/share/keyrings/llvm.gpg
    - echo "deb [signed-by=/usr/share/keyrings/llvm.gpg] http://apt.llvm.org/noble/ llvm-toolchain-noble-21 main" > /etc/apt/sources.list.d/llvm.list
    - apt-get update
    - apt-get install -y --no-install-recommends clang-format-21
    - ln -sf /usr/bin/clang-format-21 /usr/local/bin/clang-format
    - clang-format --version
    - chmod +x ./configs/format-cpp.sh
  script:
    - ./configs/format-cpp.sh . check
  rules:
    - when: always