[mesh]
Lx = 10         # domain length in x
Ly = 10         # domain length in y
nG = 2          # number of ghost cells
Nx = 50         # spatial resolution in x
Ny = 50         # spatial resolution in y
spatial_unit_x = "m"
spatial_unit_y = "m"
spatial_unit_h = "m"

[bathymetry]
type = "GaussHill"               # [Flat, GaussHill, None]
b0 = 1.0                    # Flat, GaussHill
bathy_x0 = 5.0
bathy_y0 = 5.0
bathy_sigma_x = 1.0
bathy_sigma_y = 1.0
bathy_peak_height = 1.0


[boundary]
type = "ReflectingWalls"

[initial_condition]
type = "GaussInitial"       # [GaussInitial, StillWater, DamBreak, DamBreakRadial]
h0 = 1.0                        # for GaussInitial OR StillWater OR DamBreak OR DamBreakRadial
peak_height = 2.0               # GaussInitial
x0 = 2.0                        # GaussInitial
y0 = 7.0                        # GaussInitial
sigma_x = 1                     # GaussInitial
sigma_y = 1                   # GaussInitial
dam_height = 5.0                # DamBreak OR DamBreakRadial
dam_x = 8.5                     # DamBreak
dam_x0 = 8.0                    # DamBreakRadial
dam_y0 = 8.0                    # DamBreakRadial
dam_radius = 3.0                # DamBreakRadial



[solver]
reconstruction = "MUSCL"       # [PiecewiseConst, MUSCL]
riemann = "HLL"                     # [Rusanov, HLL, ROE]
time = "SSPRK3"
limiter = "minmod"

[time]
end_time = 5.0
time_steps = 1000
cfl = 0.45
time_unit = "s"
save_every = 10        # every * step gets written out

[backend]
type = "OpenMP"     # [Serial, OptimizedSerial, OpenMP]
threads = 8

[sanity_checks]
mass_conservation = false        # [true, false] -> throws runtime errors and exits programs | default threshold: 1e-10
mass_threshold = 1e-11
positivity = true
debug = true                    # only this will print into output_path
output_path = "output/sanity_checks.nc"

[output]
compute_eta = true              # estimates ETA (based on first 100 time steps)
path = "output/simulation.nc"